### ISSUE TITLE
Create VueJS Frontend

### ISSUE THREAD

**Issue by amy-keibler** [amy-keibler/game-night#2]
- [x] Init project using Vue CLI
- [x] Enable PWA support and verify PWA prod build works via Chrome Lighthouse
- [x] Should live under `frontend`
- [x] Add concise dev info to `frontend/README.md` 
- [x] Add Wiki page for verbose Frontend dev info with links to guides, docs, and info on how Vue was installed

**Comment by allisonsierra** [comment]
Some quick findings:
- Definitely use the Vue CLI, especially when doing Typescript projects
- PWA was sooooo easy to just have ready out of the box post-install
- The default CSS is already very mobile friendly so I vote avoiding CSS frameworks until we have a good reason
- When we're ready to add other tools for unit testing, etc, try to stick with the recommended Vue ecosystem tools unless other tools offer compelling reasons.
